version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.2

    working_directory: ~/repo

    environment:
      - NODE_ENV: development

    steps:
      - checkout
      - run: yarn
      - run: yarn test
