version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5

    working_directory: ~/repo

    dependencies:
      override:
        - yarn
      cache_directories:
        - ~/.cache/yarn

    environment:
      - PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
      - NODE_ENV: test

    steps:
      - checkout
      - run: yarn
      - run: yarn test
