version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.5

    working_directory: ~/repo

    environment:
      - NODE_ENV: development

    steps:
      - checkout
      - run: yarn install
      - run: yarn add babel-core
      - run: yarn test
